[window]
dynamic_padding = true
opacity = 1
padding = { x = 20, y = 20 }
dimensions = { columns = 90, lines = 30 }
startup_mode = "Maximized"
decorations = "None"

[font]
size = 11.0
builtin_box_drawing = true
normal      = { family = "FiraCode Nerd Font", style = "Light" }
bold        = { family = "FiraCode Nerd Font", style = "Medium" }
italic      = { family = "FiraCode Nerd Font", style = "Light Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Medium Italic" }

[colors]
primary = { foreground = "#000000", background = "#fafafa" }
selection = { text = "#000000", background = "#d8d3d3" }

[colors.normal]
black = "#000000"
blue = "#005fd7"
cyan = "#0087af"
green = "#005f00"
magenta = "#5f00d7"
red = "#b80000"
white = "#b2b2b2"
yellow = "#d75f00"

[colors.bright]
black = "#585858"
blue = "#005fd7"
cyan = "#0087af"
green = "#005f00"
magenta = "#5f00d7"
red = "#b80000"
white = "#b2b2b2"
yellow = "#d75f00"

[colors.hints]
start = { foreground = "#fafafa", background = "#000000" }
end   = { foreground = "#000000", background = "#fafafa" }

[selection]
save_to_clipboard = true

# hyperlinks
[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
command = "xdg-open"
hyperlinks = true
post_processing = true
binding = { key = "U", mods = "Alt" }
mouse = { enabled = true, mods = "None" }

# quickly paste git sha on screen
[[hints.enabled]]
regex = "([a-f0-9]{40})|([a-f0-9]{12})|([a-f0-9]{7})"
action = "Paste"
post_processing = true
binding = { key = "G", mods = "Alt" }

[keyboard]
bindings = [
  { key = "N",     mods = "Control|Shift", action = "CreateNewWindow"  },
  { key = "O",     mods = "Control|Shift", action = "ToggleViMode"     },
  { key = "L",     mods = "Control|Shift", action = "ClearSelection"   },

  { key = "R",     mods = "Control|Shift", action = "SearchBackward"   },
  { key = "S",     mods = "Control|Shift", action = "SearchForward"    },

  { key = ">",     mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "<",     mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "?",     mods = "Control|Shift", action = "ResetFontSize"    },
]

[mouse]
hide_when_typing = true
