[shell]
program = "tmux"
args = ["new-session", "-As", "default"]

[window]
dynamic_padding = true
opacity = 1
padding = { x = 5, y = 5 }
dimensions = { columns = 90, lines = 30 }
startup_mode = "Maximized"
decorations = "None"

[font]
size = 11.0
builtin_box_drawing = true
normal      = { family = "FiraCode Nerd Font", style = "Light" }
bold        = { family = "FiraCode Nerd Font", style = "Medium" }
italic      = { family = "FiraCode Nerd Font", style = "Light Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Medium Italic" }

[colors]
primary = { foreground = "#000000", background = "#f4e4e1" }
selection = { text = "#000000", background = "#e3bcb5" }

[colors.normal]
black = "#000000"
blue = "#005fd7"
cyan = "#0087af"
green = "#005f00"
magenta = "#5f00d7"
red = "#b80000"
white = "#b2b2b2"
yellow = "#d75f00"

[colors.bright]
black = "#585858"
blue = "#005fd7"
cyan = "#0087af"
green = "#005f00"
magenta = "#5f00d7"
red = "#b80000"
white = "#b2b2b2"
yellow = "#d75f00"

[colors.hints]
start = { foreground = "#e3bcb5", background = "#1d1f21" }
end   = { foreground = "#1d1f21", background = "#e3bcb5" }

[selection]
save_to_clipboard = true

# hyperlinks
[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
command = "xdg-open"
hyperlinks = true
post_processing = true
binding = { key = "J", mods = "Alt" }
mouse = { enabled = true, mods = "None" }

# quickly paste git sha on screen
[[hints.enabled]]
regex = "([a-f0-9]{40})|([a-f0-9]{12})|([a-f0-9]{7})"
action = "Paste"
post_processing = true
binding = { key = "G", mods = "Control" }

[keyboard]
bindings = [
  { key = "N",     mods = "Control|Shift", action = "CreateNewWindow"  },

  { key = "J",     mods = "Control|Shift", action = "ScrollLineDown"   },
  { key = "K",     mods = "Control|Shift", action = "ScrollLineUp"     },
  { key = "F",     mods = "Control|Shift", action = "ScrollPageDown"   },
  { key = "B",     mods = "Control|Shift", action = "ScrollPageUp"     },

  { key = "O",     mods = "Control|Shift", action = "ToggleViMode"     },
  { key = "S",     mods = "Control|Shift", action = "SearchBackward"   },

  { key = "Plus",  mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control",       action = "DecreaseFontSize" },
  { key = "0",     mods = "Control",       action = "ResetFontSize"    },
]

[mouse]
hide_when_typing = true
