#!/bin/sh
set -eu

last="$(ratpoison -c 'groups' \
  | grep '[[:digit:]]*+' \
  | tr '+' ' ' \
  | awk '{ print $1 }')"

cur="$(ratpoison -c 'groups' \
  | grep '[[:digit:]]*\*' \
  | tr '*' ' ' \
  | awk '{ print $1 }')"

ratpoison -c "setenv gf_$last $(ratpoison -c "fdump")"
ratpoison -c "frestore $(ratpoison -c "getenv gf_$cur")" \
  || ratpoison -c only && ratpoison -c 'select 0'
