#!/bin/sh
set -eu

NUM="${1:-1}"
GRP="$(ratpoison -c 'groups' \
  | grep '[[:digit:]]*\*' \
  | tr '*' ' ' \
  | awk '{ print $1 }')"

ratpoison -c "frestore $(ratpoison -c "getenv fs_${GRP}_${NUM}")"
