#!/bin/zsh
# use a function to set the prompt according to the mode we're in
PS1=""
# hostname in white, only if ssh-ed into a machine
[[ -n $SSH_CLIENT ]] && PS1+="%B%m%b "
# prompt character
# insert/emacs mode: red # if root, white > else
# command mode: red : if root, white : else
if [[ $1 == "vicmd" ]]; then
  PS1+="%B%0(#.%F{red}:%f.:)%b "
else
  PS1+="%B%0(#.%F{red}#%f.>)%b "
fi

# just prepend the parser status (function, for, while, etc)
PS2="%_ $PS1"

RPS1=""
# number of running background jobs in green if >0
RPS1+="%1(j.[%F{green}%j%f].)"
# pwd in blue
RPS1+=" %B%F{blue}%~%f%b"
