[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Code/dotfiles"
desc = "Cd to dotfiles"

[[mgr.prepend_keymap]]
on   = "J"
run  = ["leave", "arrow next", "enter"]
desc = "Change to next parent directory"

[[mgr.prepend_keymap]]
on   = "K"
run  = ["leave", "arrow prev", "enter"]
desc = "Change to previous parent directory"
