#!/usr/bin/env bash

echo ''

function say() {
  echo "[34;1m::[0;37m $*"
}

function quit() {
  say 'Cleaning Up...'
  rm -f ~/tmp/pkglist ~/tmp/aurlist
  exit $1
}

function TRAPINT() {
  echo "[31;1m::[0;37m Caught SIGINT, aborting."
  quit 1
}

