style = "full"
inline_height = 0

show_help = false
sync_frequency = "10m"

history_filter = [
  "^ls$",
  "^ls ",
  "^la$",
  "^la ",
  "^lsr$",
  "^lsr ",
  "^cd$",
  "^cd ",
  "^c$",
  "^c ",
]

[sync]
records = true
