#!/bin/zsh
# create a simple script that can be used to 'duplicate' a system
print '#!/bin/sh'"\n" > apt-copy.sh

cmd='aptitude install'

for p in ${(f)"$(aptitude search -F "%p" --disable-columns \~i)"}; {
    cmd="${cmd} ${p}"
}

print $cmd "\n" >> apt-copy.sh

chmod +x apt-copy.sh
