#!/bin/sh

if command -v ctags >/dev/null 2>&1
then
  set -e
  PATH="/usr/bin:$PATH"
  trap 'rm -f .git/tags.$$' EXIT

  if test -f .git/exclude; then
    ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=@.git/exclude
  else
    echo "[ctags] no excludes" >&2
    ctags --tag-relative -Rf.git/tags.$$ --exclude=.git
  fi
  mv .git/tags.$$ .git/tags
fi
